### PR TITLE
fix almost everything

### PR DESCRIPTION
**Pull request by k2helix**
I changed some things to make it work in replugged on latest stable (not tested on canary).

However, there is something that I did not fix completely, the user context menu. Something unknown makes it work on some servers and crash on others because of an infinite loop, so I added an array with clicked users to avoid that crash. Problem is that the context menu now only shows the first time you right click on someone, and not the following right clicks, as the user id is now in the array. As I don't really know how to improve it, I'll just leave it like that. If someone wants to take a look it is at Modules/Patcher/General.js

Everything else I tested works fine.

### CODE REVIEW

**Comment by userXinos** [comment]
ah, someone still remembers this plugin and uses pc

**Comment by k2helix** [comment]
Not Powercord but its active fork, Replugged.

**Comment by userXinos** [comment]
seems to work stably, but I can't solve the problem when rendering the menu during the first incilation

**Comment by k2helix** [comment]
yeah the user context menu keeps crashing on some servers, any idea? I asked in Replugged's server but didn't find a solution

**Comment by userXinos** [comment]
What servers ?

**Comment by k2helix** [comment]
yup, I wasn't able to find any difference between servers where it crashes and it does not, so that's why I added this.usedMenus

**Comment by userXinos** [comment]
found! this happens on servers where the user has an item in the "Apps" menu

**Comment by k2helix** [comment]
Oh really? That's weird, I looked everywhere: number of commands, features, system channels... but did not that think about that. Brilliant!

So do you think there is anything we can do or just check if the Apps menu exists and then stop?

**Comment by k2helix** [comment]
Maybe we can check if the guild has commands of that type before rendering

**Comment by userXinos** [comment]
good idea, ok, we found out that it is not possible to patch the context menu on this guild, and then what to do? just skip this step ... ?

**Comment by k2helix** [comment]
https://github.com/k2helix/image-tools/blob/main/modules/Patcher/General.js#L82

here, we could do the check with the guildId menu provides, using the getGuild module and if there are commands of that type, return menu without patching anything

**Comment by k2helix** [comment]
it is the 2 here, it should be easy to do, I'll commit as soon as I can
image

**Comment by k2helix** [comment]
Done.

As I said, this won't render if the guild has application user commands, so even if the user has no access to them it won't render and thus won't show the Image menu

**Comment by userXinos** [comment]
fixes #27
close #31
close #30

**Comment by userXinos** [comment]
now there is a problem when the patch does not render for the first time

**Comment by k2helix** [comment]
it also happens for me on other plugins such as ViewRaw, I don't think there is anything we can do

**Comment by userXinos** [comment]
> BTW maybe it is better to move the check where I put it,

this should keep the code clean i think. I don't think a couple of passing through a couple of methods will be noticeable at all, the most costly is the render is skipped

**Comment by k2helix** [comment]
I see. Feel free to merge now then. Thanks!

**Comment by userXinos** [comment]
good job

**Pull request merged**
